<?php

use Illuminate\Database\Seeder;
use App\Cor;

class CorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      if (Cor::where('nome', 'Black')->count()) { $cor = Cor::where('nome', 'Black')->first(); $cor->nome = 'Black'; $cor->hexadecimal = '#000000'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Black'; $cor->hexadecimal = '#000000'; $cor->save(); }
      if (Cor::where('nome', 'DimGray')->count()) { $cor = Cor::where('nome', 'DimGray')->first(); $cor->nome = 'DimGray'; $cor->hexadecimal = '#696969'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DimGray'; $cor->hexadecimal = '#696969'; $cor->save(); }
      if (Cor::where('nome', 'Gray')->count()) { $cor = Cor::where('nome', 'Gray')->first(); $cor->nome = 'Gray'; $cor->hexadecimal = '#808080'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Gray'; $cor->hexadecimal = '#808080'; $cor->save(); }
      if (Cor::where('nome', 'DarkGray')->count()) { $cor = Cor::where('nome', 'DarkGray')->first(); $cor->nome = 'DarkGray'; $cor->hexadecimal = '#A9A9A9'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkGray'; $cor->hexadecimal = '#A9A9A9'; $cor->save(); }
      if (Cor::where('nome', 'Silver')->count()) { $cor = Cor::where('nome', 'Silver')->first(); $cor->nome = 'Silver'; $cor->hexadecimal = '#C0C0C0'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Silver'; $cor->hexadecimal = '#C0C0C0'; $cor->save(); }
      if (Cor::where('nome', 'LightGrey')->count()) { $cor = Cor::where('nome', 'LightGrey')->first(); $cor->nome = 'LightGrey'; $cor->hexadecimal = '#D3D3D3'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightGrey'; $cor->hexadecimal = '#D3D3D3'; $cor->save(); }
      if (Cor::where('nome', 'Gainsboro')->count()) { $cor = Cor::where('nome', 'Gainsboro')->first(); $cor->nome = 'Gainsboro'; $cor->hexadecimal = '#DCDCDC'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Gainsboro'; $cor->hexadecimal = '#DCDCDC'; $cor->save(); }
      if (Cor::where('nome', 'White')->count()) { $cor = Cor::where('nome', 'White')->first(); $cor->nome = 'White'; $cor->hexadecimal = '#FFFFFF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'White'; $cor->hexadecimal = '#FFFFFF'; $cor->save(); }
      if (Cor::where('nome', 'SlateBlue')->count()) { $cor = Cor::where('nome', 'SlateBlue')->first(); $cor->nome = 'SlateBlue'; $cor->hexadecimal = '#6A5ACD'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SlateBlue'; $cor->hexadecimal = '#6A5ACD'; $cor->save(); }
      if (Cor::where('nome', 'DarkSlateBlue')->count()) { $cor = Cor::where('nome', 'DarkSlateBlue')->first(); $cor->nome = 'DarkSlateBlue'; $cor->hexadecimal = '#483D8B'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkSlateBlue'; $cor->hexadecimal = '#483D8B'; $cor->save(); }
      if (Cor::where('nome', 'MidnightBlue')->count()) { $cor = Cor::where('nome', 'MidnightBlue')->first(); $cor->nome = 'MidnightBlue'; $cor->hexadecimal = '#191970'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MidnightBlue'; $cor->hexadecimal = '#191970'; $cor->save(); }
      if (Cor::where('nome', 'Navy')->count()) { $cor = Cor::where('nome', 'Navy')->first(); $cor->nome = 'Navy'; $cor->hexadecimal = '#000080'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Navy'; $cor->hexadecimal = '#000080'; $cor->save(); }
      if (Cor::where('nome', 'DarkBlue')->count()) { $cor = Cor::where('nome', 'DarkBlue')->first(); $cor->nome = 'DarkBlue'; $cor->hexadecimal = '#00008B'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkBlue'; $cor->hexadecimal = '#00008B'; $cor->save(); }
      if (Cor::where('nome', 'MediumBlue')->count()) { $cor = Cor::where('nome', 'MediumBlue')->first(); $cor->nome = 'MediumBlue'; $cor->hexadecimal = '#0000CD'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumBlue'; $cor->hexadecimal = '#0000CD'; $cor->save(); }
      if (Cor::where('nome', 'Blue')->count()) { $cor = Cor::where('nome', 'Blue')->first(); $cor->nome = 'Blue'; $cor->hexadecimal = '#0000FF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Blue'; $cor->hexadecimal = '#0000FF'; $cor->save(); }
      if (Cor::where('nome', 'CornflowerBlue')->count()) { $cor = Cor::where('nome', 'CornflowerBlue')->first(); $cor->nome = 'CornflowerBlue'; $cor->hexadecimal = '#6495ED'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'CornflowerBlue'; $cor->hexadecimal = '#6495ED'; $cor->save(); }
      if (Cor::where('nome', 'RoyalBlue')->count()) { $cor = Cor::where('nome', 'RoyalBlue')->first(); $cor->nome = 'RoyalBlue'; $cor->hexadecimal = '#4169E1'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'RoyalBlue'; $cor->hexadecimal = '#4169E1'; $cor->save(); }
      if (Cor::where('nome', 'DodgerBlue')->count()) { $cor = Cor::where('nome', 'DodgerBlue')->first(); $cor->nome = 'DodgerBlue'; $cor->hexadecimal = '#1E90FF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DodgerBlue'; $cor->hexadecimal = '#1E90FF'; $cor->save(); }
      if (Cor::where('nome', 'DeepSkyBlue')->count()) { $cor = Cor::where('nome', 'DeepSkyBlue')->first(); $cor->nome = 'DeepSkyBlue'; $cor->hexadecimal = '#00BFFF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DeepSkyBlue'; $cor->hexadecimal = '#00BFFF'; $cor->save(); }
      if (Cor::where('nome', 'LightSkyBlue')->count()) { $cor = Cor::where('nome', 'LightSkyBlue')->first(); $cor->nome = 'LightSkyBlue'; $cor->hexadecimal = '#87CEFA'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightSkyBlue'; $cor->hexadecimal = '#87CEFA'; $cor->save(); }
      if (Cor::where('nome', 'SkyBlue')->count()) { $cor = Cor::where('nome', 'SkyBlue')->first(); $cor->nome = 'SkyBlue'; $cor->hexadecimal = '#87CEEB'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SkyBlue'; $cor->hexadecimal = '#87CEEB'; $cor->save(); }
      if (Cor::where('nome', 'LightBlue')->count()) { $cor = Cor::where('nome', 'LightBlue')->first(); $cor->nome = 'LightBlue'; $cor->hexadecimal = '#ADD8E6'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightBlue'; $cor->hexadecimal = '#ADD8E6'; $cor->save(); }
      if (Cor::where('nome', 'SteelBlue')->count()) { $cor = Cor::where('nome', 'SteelBlue')->first(); $cor->nome = 'SteelBlue'; $cor->hexadecimal = '#4682B4'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SteelBlue'; $cor->hexadecimal = '#4682B4'; $cor->save(); }
      if (Cor::where('nome', 'LightSteelBlue')->count()) { $cor = Cor::where('nome', 'LightSteelBlue')->first(); $cor->nome = 'LightSteelBlue'; $cor->hexadecimal = '#B0C4DE'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightSteelBlue'; $cor->hexadecimal = '#B0C4DE'; $cor->save(); }
      if (Cor::where('nome', 'SlateGray')->count()) { $cor = Cor::where('nome', 'SlateGray')->first(); $cor->nome = 'SlateGray'; $cor->hexadecimal = '#708090'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SlateGray'; $cor->hexadecimal = '#708090'; $cor->save(); }
      if (Cor::where('nome', 'LightSlateGray')->count()) { $cor = Cor::where('nome', 'LightSlateGray')->first(); $cor->nome = 'LightSlateGray'; $cor->hexadecimal = '#778899'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightSlateGray'; $cor->hexadecimal = '#778899'; $cor->save(); }
      if (Cor::where('nome', 'Aqua / Cyan')->count()) { $cor = Cor::where('nome', 'Aqua / Cyan')->first(); $cor->nome = 'Aqua / Cyan'; $cor->hexadecimal = '#00FFFF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Aqua / Cyan'; $cor->hexadecimal = '#00FFFF'; $cor->save(); }
      if (Cor::where('nome', 'DarkTurquoise')->count()) { $cor = Cor::where('nome', 'DarkTurquoise')->first(); $cor->nome = 'DarkTurquoise'; $cor->hexadecimal = '#00CED1'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkTurquoise'; $cor->hexadecimal = '#00CED1'; $cor->save(); }
      if (Cor::where('nome', 'Turquoise')->count()) { $cor = Cor::where('nome', 'Turquoise')->first(); $cor->nome = 'Turquoise'; $cor->hexadecimal = '#40E0D0'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Turquoise'; $cor->hexadecimal = '#40E0D0'; $cor->save(); }
      if (Cor::where('nome', 'MediumTurquoise')->count()) { $cor = Cor::where('nome', 'MediumTurquoise')->first(); $cor->nome = 'MediumTurquoise'; $cor->hexadecimal = '#48D1CC'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumTurquoise'; $cor->hexadecimal = '#48D1CC'; $cor->save(); }
      if (Cor::where('nome', 'LightSeaGreen')->count()) { $cor = Cor::where('nome', 'LightSeaGreen')->first(); $cor->nome = 'LightSeaGreen'; $cor->hexadecimal = '#20B2AA'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightSeaGreen'; $cor->hexadecimal = '#20B2AA'; $cor->save(); }
      if (Cor::where('nome', 'DarkCyan')->count()) { $cor = Cor::where('nome', 'DarkCyan')->first(); $cor->nome = 'DarkCyan'; $cor->hexadecimal = '#008B8B'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkCyan'; $cor->hexadecimal = '#008B8B'; $cor->save(); }
      if (Cor::where('nome', 'Teal')->count()) { $cor = Cor::where('nome', 'Teal')->first(); $cor->nome = 'Teal'; $cor->hexadecimal = '#008B8B'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Teal'; $cor->hexadecimal = '#008B8B'; $cor->save(); }
      if (Cor::where('nome', 'Aquamarine')->count()) { $cor = Cor::where('nome', 'Aquamarine')->first(); $cor->nome = 'Aquamarine'; $cor->hexadecimal = '#7FFFD4'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Aquamarine'; $cor->hexadecimal = '#7FFFD4'; $cor->save(); }
      if (Cor::where('nome', 'MediumAquamarine')->count()) { $cor = Cor::where('nome', 'MediumAquamarine')->first(); $cor->nome = 'MediumAquamarine'; $cor->hexadecimal = '#66CDAA'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumAquamarine'; $cor->hexadecimal = '#66CDAA'; $cor->save(); }
      if (Cor::where('nome', 'CadetBlue')->count()) { $cor = Cor::where('nome', 'CadetBlue')->first(); $cor->nome = 'CadetBlue'; $cor->hexadecimal = '#5F9EA0'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'CadetBlue'; $cor->hexadecimal = '#5F9EA0'; $cor->save(); }
      if (Cor::where('nome', 'DarkSlateGray')->count()) { $cor = Cor::where('nome', 'DarkSlateGray')->first(); $cor->nome = 'DarkSlateGray'; $cor->hexadecimal = '#2F4F4F'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkSlateGray'; $cor->hexadecimal = '#2F4F4F'; $cor->save(); }
      if (Cor::where('nome', 'MediumSpringGreen')->count()) { $cor = Cor::where('nome', 'MediumSpringGreen')->first(); $cor->nome = 'MediumSpringGreen'; $cor->hexadecimal = '#00FA9A'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumSpringGreen'; $cor->hexadecimal = '#00FA9A'; $cor->save(); }
      if (Cor::where('nome', 'SpringGreen')->count()) { $cor = Cor::where('nome', 'SpringGreen')->first(); $cor->nome = 'SpringGreen'; $cor->hexadecimal = '#00FF7F'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SpringGreen'; $cor->hexadecimal = '#00FF7F'; $cor->save(); }
      if (Cor::where('nome', 'PaleGreen')->count()) { $cor = Cor::where('nome', 'PaleGreen')->first(); $cor->nome = 'PaleGreen'; $cor->hexadecimal = '#98FB98'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'PaleGreen'; $cor->hexadecimal = '#98FB98'; $cor->save(); }
      if (Cor::where('nome', 'LightGreen')->count()) { $cor = Cor::where('nome', 'LightGreen')->first(); $cor->nome = 'LightGreen'; $cor->hexadecimal = '#90EE90'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightGreen'; $cor->hexadecimal = '#90EE90'; $cor->save(); }
      if (Cor::where('nome', 'DarkSeaGreen')->count()) { $cor = Cor::where('nome', 'DarkSeaGreen')->first(); $cor->nome = 'DarkSeaGreen'; $cor->hexadecimal = '#8FBC8F'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkSeaGreen'; $cor->hexadecimal = '#8FBC8F'; $cor->save(); }
      if (Cor::where('nome', 'MediumSeaGreen')->count()) { $cor = Cor::where('nome', 'MediumSeaGreen')->first(); $cor->nome = 'MediumSeaGreen'; $cor->hexadecimal = '#3CB371'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumSeaGreen'; $cor->hexadecimal = '#3CB371'; $cor->save(); }
      if (Cor::where('nome', 'SeaGreen')->count()) { $cor = Cor::where('nome', 'SeaGreen')->first(); $cor->nome = 'SeaGreen'; $cor->hexadecimal = '#2E8B57'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SeaGreen'; $cor->hexadecimal = '#2E8B57'; $cor->save(); }
      if (Cor::where('nome', 'DarkGreen')->count()) { $cor = Cor::where('nome', 'DarkGreen')->first(); $cor->nome = 'DarkGreen'; $cor->hexadecimal = '#006400'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkGreen'; $cor->hexadecimal = '#006400'; $cor->save(); }
      if (Cor::where('nome', 'Green')->count()) { $cor = Cor::where('nome', 'Green')->first(); $cor->nome = 'Green'; $cor->hexadecimal = '#008000'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Green'; $cor->hexadecimal = '#008000'; $cor->save(); }
      if (Cor::where('nome', 'ForestGreen')->count()) { $cor = Cor::where('nome', 'ForestGreen')->first(); $cor->nome = 'ForestGreen'; $cor->hexadecimal = '#228B22'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'ForestGreen'; $cor->hexadecimal = '#228B22'; $cor->save(); }
      if (Cor::where('nome', 'LimeGreen')->count()) { $cor = Cor::where('nome', 'LimeGreen')->first(); $cor->nome = 'LimeGreen'; $cor->hexadecimal = '#32CD32'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LimeGreen'; $cor->hexadecimal = '#32CD32'; $cor->save(); }
      if (Cor::where('nome', 'Lime')->count()) { $cor = Cor::where('nome', 'Lime')->first(); $cor->nome = 'Lime'; $cor->hexadecimal = '#00FF00'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Lime'; $cor->hexadecimal = '#00FF00'; $cor->save(); }
      if (Cor::where('nome', 'LawnGreen')->count()) { $cor = Cor::where('nome', 'LawnGreen')->first(); $cor->nome = 'LawnGreen'; $cor->hexadecimal = '#7CFC00'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LawnGreen'; $cor->hexadecimal = '#7CFC00'; $cor->save(); }
      if (Cor::where('nome', 'Chartreuse')->count()) { $cor = Cor::where('nome', 'Chartreuse')->first(); $cor->nome = 'Chartreuse'; $cor->hexadecimal = '#7FFF00'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Chartreuse'; $cor->hexadecimal = '#7FFF00'; $cor->save(); }
      if (Cor::where('nome', 'GreenYellow')->count()) { $cor = Cor::where('nome', 'GreenYellow')->first(); $cor->nome = 'GreenYellow'; $cor->hexadecimal = '#ADFF2F'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'GreenYellow'; $cor->hexadecimal = '#ADFF2F'; $cor->save(); }
      if (Cor::where('nome', 'YellowGreen')->count()) { $cor = Cor::where('nome', 'YellowGreen')->first(); $cor->nome = 'YellowGreen'; $cor->hexadecimal = '#9ACD32'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'YellowGreen'; $cor->hexadecimal = '#9ACD32'; $cor->save(); }
      if (Cor::where('nome', 'OliveDrab')->count()) { $cor = Cor::where('nome', 'OliveDrab')->first(); $cor->nome = 'OliveDrab'; $cor->hexadecimal = '#6B8E23'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'OliveDrab'; $cor->hexadecimal = '#6B8E23'; $cor->save(); }
      if (Cor::where('nome', 'DarkOliveGreen')->count()) { $cor = Cor::where('nome', 'DarkOliveGreen')->first(); $cor->nome = 'DarkOliveGreen'; $cor->hexadecimal = '#556B2F'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkOliveGreen'; $cor->hexadecimal = '#556B2F'; $cor->save(); }
      if (Cor::where('nome', 'Olive')->count()) { $cor = Cor::where('nome', 'Olive')->first(); $cor->nome = 'Olive'; $cor->hexadecimal = '#808000'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Olive'; $cor->hexadecimal = '#808000'; $cor->save(); }
      if (Cor::where('nome', 'DarkKhaki')->count()) { $cor = Cor::where('nome', 'DarkKhaki')->first(); $cor->nome = 'DarkKhaki'; $cor->hexadecimal = '#BDB76B'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkKhaki'; $cor->hexadecimal = '#BDB76B'; $cor->save(); }
      if (Cor::where('nome', 'Goldenrod')->count()) { $cor = Cor::where('nome', 'Goldenrod')->first(); $cor->nome = 'Goldenrod'; $cor->hexadecimal = '#DAA520'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Goldenrod'; $cor->hexadecimal = '#DAA520'; $cor->save(); }
      if (Cor::where('nome', 'DarkGoldenrod')->count()) { $cor = Cor::where('nome', 'DarkGoldenrod')->first(); $cor->nome = 'DarkGoldenrod'; $cor->hexadecimal = '#B8860B'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkGoldenrod'; $cor->hexadecimal = '#B8860B'; $cor->save(); }
      if (Cor::where('nome', 'SaddleBrown')->count()) { $cor = Cor::where('nome', 'SaddleBrown')->first(); $cor->nome = 'SaddleBrown'; $cor->hexadecimal = '#8B4513'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SaddleBrown'; $cor->hexadecimal = '#8B4513'; $cor->save(); }
      if (Cor::where('nome', 'Sienna')->count()) { $cor = Cor::where('nome', 'Sienna')->first(); $cor->nome = 'Sienna'; $cor->hexadecimal = '#A0522D'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Sienna'; $cor->hexadecimal = '#A0522D'; $cor->save(); }
      if (Cor::where('nome', 'RosyBrown')->count()) { $cor = Cor::where('nome', 'RosyBrown')->first(); $cor->nome = 'RosyBrown'; $cor->hexadecimal = '#BC8F8F'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'RosyBrown'; $cor->hexadecimal = '#BC8F8F'; $cor->save(); }
      if (Cor::where('nome', 'Peru')->count()) { $cor = Cor::where('nome', 'Peru')->first(); $cor->nome = 'Peru'; $cor->hexadecimal = '#CD853F'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Peru'; $cor->hexadecimal = '#CD853F'; $cor->save(); }
      if (Cor::where('nome', 'Chocolate')->count()) { $cor = Cor::where('nome', 'Chocolate')->first(); $cor->nome = 'Chocolate'; $cor->hexadecimal = '#D2691E'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Chocolate'; $cor->hexadecimal = '#D2691E'; $cor->save(); }
      if (Cor::where('nome', 'SandyBrown')->count()) { $cor = Cor::where('nome', 'SandyBrown')->first(); $cor->nome = 'SandyBrown'; $cor->hexadecimal = '#F4A460'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'SandyBrown'; $cor->hexadecimal = '#F4A460'; $cor->save(); }
      if (Cor::where('nome', 'NavajoWhite')->count()) { $cor = Cor::where('nome', 'NavajoWhite')->first(); $cor->nome = 'NavajoWhite'; $cor->hexadecimal = '#FFDEAD'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'NavajoWhite'; $cor->hexadecimal = '#FFDEAD'; $cor->save(); }
      if (Cor::where('nome', 'Wheat')->count()) { $cor = Cor::where('nome', 'Wheat')->first(); $cor->nome = 'Wheat'; $cor->hexadecimal = '#F5DEB3'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Wheat'; $cor->hexadecimal = '#F5DEB3'; $cor->save(); }
      if (Cor::where('nome', 'BurlyWood')->count()) { $cor = Cor::where('nome', 'BurlyWood')->first(); $cor->nome = 'BurlyWood'; $cor->hexadecimal = '#DEB887'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'BurlyWood'; $cor->hexadecimal = '#DEB887'; $cor->save(); }
      if (Cor::where('nome', 'Tan')->count()) { $cor = Cor::where('nome', 'Tan')->first(); $cor->nome = 'Tan'; $cor->hexadecimal = '#D2B48C'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Tan'; $cor->hexadecimal = '#D2B48C'; $cor->save(); }
      if (Cor::where('nome', 'MediumSlateBlue')->count()) { $cor = Cor::where('nome', 'MediumSlateBlue')->first(); $cor->nome = 'MediumSlateBlue'; $cor->hexadecimal = '#7B68EE'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumSlateBlue'; $cor->hexadecimal = '#7B68EE'; $cor->save(); }
      if (Cor::where('nome', 'MediumPurple')->count()) { $cor = Cor::where('nome', 'MediumPurple')->first(); $cor->nome = 'MediumPurple'; $cor->hexadecimal = '#9370DB'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumPurple'; $cor->hexadecimal = '#9370DB'; $cor->save(); }
      if (Cor::where('nome', 'BlueViolet')->count()) { $cor = Cor::where('nome', 'BlueViolet')->first(); $cor->nome = 'BlueViolet'; $cor->hexadecimal = '#8A2BE2'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'BlueViolet'; $cor->hexadecimal = '#8A2BE2'; $cor->save(); }
      if (Cor::where('nome', 'Indigo')->count()) { $cor = Cor::where('nome', 'Indigo')->first(); $cor->nome = 'Indigo'; $cor->hexadecimal = '#4B0082'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Indigo'; $cor->hexadecimal = '#4B0082'; $cor->save(); }
      if (Cor::where('nome', 'DarkViolet')->count()) { $cor = Cor::where('nome', 'DarkViolet')->first(); $cor->nome = 'DarkViolet'; $cor->hexadecimal = '#9400D3'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkViolet'; $cor->hexadecimal = '#9400D3'; $cor->save(); }
      if (Cor::where('nome', 'DarkOrchid')->count()) { $cor = Cor::where('nome', 'DarkOrchid')->first(); $cor->nome = 'DarkOrchid'; $cor->hexadecimal = '#9932CC'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkOrchid'; $cor->hexadecimal = '#9932CC'; $cor->save(); }
      if (Cor::where('nome', 'MediumOrchid')->count()) { $cor = Cor::where('nome', 'MediumOrchid')->first(); $cor->nome = 'MediumOrchid'; $cor->hexadecimal = '#BA55D3'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumOrchid'; $cor->hexadecimal = '#BA55D3'; $cor->save(); }
      if (Cor::where('nome', 'Purple')->count()) { $cor = Cor::where('nome', 'Purple')->first(); $cor->nome = 'Purple'; $cor->hexadecimal = '#800080'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Purple'; $cor->hexadecimal = '#800080'; $cor->save(); }
      if (Cor::where('nome', 'DarkMagenta')->count()) { $cor = Cor::where('nome', 'DarkMagenta')->first(); $cor->nome = 'DarkMagenta'; $cor->hexadecimal = '#8B008B'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkMagenta'; $cor->hexadecimal = '#8B008B'; $cor->save(); }
      if (Cor::where('nome', 'Fuchsia / Magenta')->count()) { $cor = Cor::where('nome', 'Fuchsia / Magenta')->first(); $cor->nome = 'Fuchsia / Magenta'; $cor->hexadecimal = '#FF00FF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Fuchsia / Magenta'; $cor->hexadecimal = '#FF00FF'; $cor->save(); }
      if (Cor::where('nome', 'Violet')->count()) { $cor = Cor::where('nome', 'Violet')->first(); $cor->nome = 'Violet'; $cor->hexadecimal = '#EE82EE'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Violet'; $cor->hexadecimal = '#EE82EE'; $cor->save(); }
      if (Cor::where('nome', 'Orchid')->count()) { $cor = Cor::where('nome', 'Orchid')->first(); $cor->nome = 'Orchid'; $cor->hexadecimal = '#DA70D6'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Orchid'; $cor->hexadecimal = '#DA70D6'; $cor->save(); }
      if (Cor::where('nome', 'Plum')->count()) { $cor = Cor::where('nome', 'Plum')->first(); $cor->nome = 'Plum'; $cor->hexadecimal = '#DDA0DD'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Plum'; $cor->hexadecimal = '#DDA0DD'; $cor->save(); }
      if (Cor::where('nome', 'MediumVioletRed')->count()) { $cor = Cor::where('nome', 'MediumVioletRed')->first(); $cor->nome = 'MediumVioletRed'; $cor->hexadecimal = '#C71585'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MediumVioletRed'; $cor->hexadecimal = '#C71585'; $cor->save(); }
      if (Cor::where('nome', 'DeepPink')->count()) { $cor = Cor::where('nome', 'DeepPink')->first(); $cor->nome = 'DeepPink'; $cor->hexadecimal = '#FF1493'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DeepPink'; $cor->hexadecimal = '#FF1493'; $cor->save(); }
      if (Cor::where('nome', 'HotPink')->count()) { $cor = Cor::where('nome', 'HotPink')->first(); $cor->nome = 'HotPink'; $cor->hexadecimal = '#FF69B4'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'HotPink'; $cor->hexadecimal = '#FF69B4'; $cor->save(); }
      if (Cor::where('nome', 'PaleVioletRed')->count()) { $cor = Cor::where('nome', 'PaleVioletRed')->first(); $cor->nome = 'PaleVioletRed'; $cor->hexadecimal = '#DB7093'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'PaleVioletRed'; $cor->hexadecimal = '#DB7093'; $cor->save(); }
      if (Cor::where('nome', 'LightPink')->count()) { $cor = Cor::where('nome', 'LightPink')->first(); $cor->nome = 'LightPink'; $cor->hexadecimal = '#FFB6C1'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightPink'; $cor->hexadecimal = '#FFB6C1'; $cor->save(); }
      if (Cor::where('nome', 'Pink')->count()) { $cor = Cor::where('nome', 'Pink')->first(); $cor->nome = 'Pink'; $cor->hexadecimal = '#FFC0CB'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Pink'; $cor->hexadecimal = '#FFC0CB'; $cor->save(); }
      if (Cor::where('nome', 'LightCoral')->count()) { $cor = Cor::where('nome', 'LightCoral')->first(); $cor->nome = 'LightCoral'; $cor->hexadecimal = '#F08080'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightCoral'; $cor->hexadecimal = '#F08080'; $cor->save(); }
      if (Cor::where('nome', 'IndianRed')->count()) { $cor = Cor::where('nome', 'IndianRed')->first(); $cor->nome = 'IndianRed'; $cor->hexadecimal = '#CD5C5C'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'IndianRed'; $cor->hexadecimal = '#CD5C5C'; $cor->save(); }
      if (Cor::where('nome', 'Crimson')->count()) { $cor = Cor::where('nome', 'Crimson')->first(); $cor->nome = 'Crimson'; $cor->hexadecimal = '#DC143C'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Crimson'; $cor->hexadecimal = '#DC143C'; $cor->save(); }
      if (Cor::where('nome', 'Maroon')->count()) { $cor = Cor::where('nome', 'Maroon')->first(); $cor->nome = 'Maroon'; $cor->hexadecimal = '#800000'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Maroon'; $cor->hexadecimal = '#800000'; $cor->save(); }
      if (Cor::where('nome', 'DarkRed')->count()) { $cor = Cor::where('nome', 'DarkRed')->first(); $cor->nome = 'DarkRed'; $cor->hexadecimal = '#8B0000'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkRed'; $cor->hexadecimal = '#8B0000'; $cor->save(); }
      if (Cor::where('nome', 'FireBrick')->count()) { $cor = Cor::where('nome', 'FireBrick')->first(); $cor->nome = 'FireBrick'; $cor->hexadecimal = '#B22222'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'FireBrick'; $cor->hexadecimal = '#B22222'; $cor->save(); }
      if (Cor::where('nome', 'Brown')->count()) { $cor = Cor::where('nome', 'Brown')->first(); $cor->nome = 'Brown'; $cor->hexadecimal = '#A52A2A'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Brown'; $cor->hexadecimal = '#A52A2A'; $cor->save(); }
      if (Cor::where('nome', 'Salmon')->count()) { $cor = Cor::where('nome', 'Salmon')->first(); $cor->nome = 'Salmon'; $cor->hexadecimal = '#FA8072'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Salmon'; $cor->hexadecimal = '#FA8072'; $cor->save(); }
      if (Cor::where('nome', 'DarkSalmon')->count()) { $cor = Cor::where('nome', 'DarkSalmon')->first(); $cor->nome = 'DarkSalmon'; $cor->hexadecimal = '#E9967A'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkSalmon'; $cor->hexadecimal = '#E9967A'; $cor->save(); }
      if (Cor::where('nome', 'LightSalmon')->count()) { $cor = Cor::where('nome', 'LightSalmon')->first(); $cor->nome = 'LightSalmon'; $cor->hexadecimal = '#FFA07A'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightSalmon'; $cor->hexadecimal = '#FFA07A'; $cor->save(); }
      if (Cor::where('nome', 'Coral')->count()) { $cor = Cor::where('nome', 'Coral')->first(); $cor->nome = 'Coral'; $cor->hexadecimal = '#FF7F50'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Coral'; $cor->hexadecimal = '#FF7F50'; $cor->save(); }
      if (Cor::where('nome', 'Tomato')->count()) { $cor = Cor::where('nome', 'Tomato')->first(); $cor->nome = 'Tomato'; $cor->hexadecimal = '#FF6347'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Tomato'; $cor->hexadecimal = '#FF6347'; $cor->save(); }
      if (Cor::where('nome', 'Red')->count()) { $cor = Cor::where('nome', 'Red')->first(); $cor->nome = 'Red'; $cor->hexadecimal = '#FF0000'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Red'; $cor->hexadecimal = '#FF0000'; $cor->save(); }
      if (Cor::where('nome', 'OrangeRed')->count()) { $cor = Cor::where('nome', 'OrangeRed')->first(); $cor->nome = 'OrangeRed'; $cor->hexadecimal = '#FF4500'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'OrangeRed'; $cor->hexadecimal = '#FF4500'; $cor->save(); }
      if (Cor::where('nome', 'DarkOrange')->count()) { $cor = Cor::where('nome', 'DarkOrange')->first(); $cor->nome = 'DarkOrange'; $cor->hexadecimal = '#FF8C00'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'DarkOrange'; $cor->hexadecimal = '#FF8C00'; $cor->save(); }
      if (Cor::where('nome', 'Orange')->count()) { $cor = Cor::where('nome', 'Orange')->first(); $cor->nome = 'Orange'; $cor->hexadecimal = '#FFA500'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Orange'; $cor->hexadecimal = '#FFA500'; $cor->save(); }
      if (Cor::where('nome', 'Gold')->count()) { $cor = Cor::where('nome', 'Gold')->first(); $cor->nome = 'Gold'; $cor->hexadecimal = '#FFD700'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Gold'; $cor->hexadecimal = '#FFD700'; $cor->save(); }
      if (Cor::where('nome', 'Yellow')->count()) { $cor = Cor::where('nome', 'Yellow')->first(); $cor->nome = 'Yellow'; $cor->hexadecimal = '#FFFF00'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Yellow'; $cor->hexadecimal = '#FFFF00'; $cor->save(); }
      if (Cor::where('nome', 'Khaki')->count()) { $cor = Cor::where('nome', 'Khaki')->first(); $cor->nome = 'Khaki'; $cor->hexadecimal = '#F0E68C'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Khaki'; $cor->hexadecimal = '#F0E68C'; $cor->save(); }
      if (Cor::where('nome', 'AliceBlue')->count()) { $cor = Cor::where('nome', 'AliceBlue')->first(); $cor->nome = 'AliceBlue'; $cor->hexadecimal = '#F0F8FF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'AliceBlue'; $cor->hexadecimal = '#F0F8FF'; $cor->save(); }
      if (Cor::where('nome', 'GhostWhite')->count()) { $cor = Cor::where('nome', 'GhostWhite')->first(); $cor->nome = 'GhostWhite'; $cor->hexadecimal = '#F8F8FF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'GhostWhite'; $cor->hexadecimal = '#F8F8FF'; $cor->save(); }
      if (Cor::where('nome', 'Snow')->count()) { $cor = Cor::where('nome', 'Snow')->first(); $cor->nome = 'Snow'; $cor->hexadecimal = '#FFFAFA'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Snow'; $cor->hexadecimal = '#FFFAFA'; $cor->save(); }
      if (Cor::where('nome', 'Seashell')->count()) { $cor = Cor::where('nome', 'Seashell')->first(); $cor->nome = 'Seashell'; $cor->hexadecimal = '#FFF5EE'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Seashell'; $cor->hexadecimal = '#FFF5EE'; $cor->save(); }
      if (Cor::where('nome', 'FloralWhite')->count()) { $cor = Cor::where('nome', 'FloralWhite')->first(); $cor->nome = 'FloralWhite'; $cor->hexadecimal = '#FFFAF0'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'FloralWhite'; $cor->hexadecimal = '#FFFAF0'; $cor->save(); }
      if (Cor::where('nome', 'WhiteSmoke')->count()) { $cor = Cor::where('nome', 'WhiteSmoke')->first(); $cor->nome = 'WhiteSmoke'; $cor->hexadecimal = '#F5F5F5'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'WhiteSmoke'; $cor->hexadecimal = '#F5F5F5'; $cor->save(); }
      if (Cor::where('nome', 'Beige')->count()) { $cor = Cor::where('nome', 'Beige')->first(); $cor->nome = 'Beige'; $cor->hexadecimal = '#F5F5DC'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Beige'; $cor->hexadecimal = '#F5F5DC'; $cor->save(); }
      if (Cor::where('nome', 'OldLace')->count()) { $cor = Cor::where('nome', 'OldLace')->first(); $cor->nome = 'OldLace'; $cor->hexadecimal = '#FDF5E6'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'OldLace'; $cor->hexadecimal = '#FDF5E6'; $cor->save(); }
      if (Cor::where('nome', 'Ivory')->count()) { $cor = Cor::where('nome', 'Ivory')->first(); $cor->nome = 'Ivory'; $cor->hexadecimal = '#FFFFF0'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Ivory'; $cor->hexadecimal = '#FFFFF0'; $cor->save(); }
      if (Cor::where('nome', 'Linen')->count()) { $cor = Cor::where('nome', 'Linen')->first(); $cor->nome = 'Linen'; $cor->hexadecimal = '#FAF0E6'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Linen'; $cor->hexadecimal = '#FAF0E6'; $cor->save(); }
      if (Cor::where('nome', 'Cornsilk')->count()) { $cor = Cor::where('nome', 'Cornsilk')->first(); $cor->nome = 'Cornsilk'; $cor->hexadecimal = '#FFF8DC'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Cornsilk'; $cor->hexadecimal = '#FFF8DC'; $cor->save(); }
      if (Cor::where('nome', 'AntiqueWhite')->count()) { $cor = Cor::where('nome', 'AntiqueWhite')->first(); $cor->nome = 'AntiqueWhite'; $cor->hexadecimal = '#FAEBD7'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'AntiqueWhite'; $cor->hexadecimal = '#FAEBD7'; $cor->save(); }
      if (Cor::where('nome', 'BlanchedAlmond')->count()) { $cor = Cor::where('nome', 'BlanchedAlmond')->first(); $cor->nome = 'BlanchedAlmond'; $cor->hexadecimal = '#FFEBCD'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'BlanchedAlmond'; $cor->hexadecimal = '#FFEBCD'; $cor->save(); }
      if (Cor::where('nome', 'Bisque')->count()) { $cor = Cor::where('nome', 'Bisque')->first(); $cor->nome = 'Bisque'; $cor->hexadecimal = '#FFE4C4'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Bisque'; $cor->hexadecimal = '#FFE4C4'; $cor->save(); }
      if (Cor::where('nome', 'LightYellow')->count()) { $cor = Cor::where('nome', 'LightYellow')->first(); $cor->nome = 'LightYellow'; $cor->hexadecimal = '#FFFFE0'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightYellow'; $cor->hexadecimal = '#FFFFE0'; $cor->save(); }
      if (Cor::where('nome', 'LemonChiffon')->count()) { $cor = Cor::where('nome', 'LemonChiffon')->first(); $cor->nome = 'LemonChiffon'; $cor->hexadecimal = '#FFFACD'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LemonChiffon'; $cor->hexadecimal = '#FFFACD'; $cor->save(); }
      if (Cor::where('nome', 'LightGoldenrodYellow')->count()) { $cor = Cor::where('nome', 'LightGoldenrodYellow')->first(); $cor->nome = 'LightGoldenrodYellow'; $cor->hexadecimal = '#FAFAD2'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightGoldenrodYellow'; $cor->hexadecimal = '#FAFAD2'; $cor->save(); }
      if (Cor::where('nome', 'PapayaWhip')->count()) { $cor = Cor::where('nome', 'PapayaWhip')->first(); $cor->nome = 'PapayaWhip'; $cor->hexadecimal = '#FFEFD5'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'PapayaWhip'; $cor->hexadecimal = '#FFEFD5'; $cor->save(); }
      if (Cor::where('nome', 'PeachPuff')->count()) { $cor = Cor::where('nome', 'PeachPuff')->first(); $cor->nome = 'PeachPuff'; $cor->hexadecimal = '#FFDAB9'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'PeachPuff'; $cor->hexadecimal = '#FFDAB9'; $cor->save(); }
      if (Cor::where('nome', 'Moccasin')->count()) { $cor = Cor::where('nome', 'Moccasin')->first(); $cor->nome = 'Moccasin'; $cor->hexadecimal = '#FFE4B5'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Moccasin'; $cor->hexadecimal = '#FFE4B5'; $cor->save(); }
      if (Cor::where('nome', 'PaleGoldenrod')->count()) { $cor = Cor::where('nome', 'PaleGoldenrod')->first(); $cor->nome = 'PaleGoldenrod'; $cor->hexadecimal = '#EEE8AA'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'PaleGoldenrod'; $cor->hexadecimal = '#EEE8AA'; $cor->save(); }
      if (Cor::where('nome', 'MistyRose')->count()) { $cor = Cor::where('nome', 'MistyRose')->first(); $cor->nome = 'MistyRose'; $cor->hexadecimal = '#FFE4E1'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MistyRose'; $cor->hexadecimal = '#FFE4E1'; $cor->save(); }
      if (Cor::where('nome', 'LavenderBlush')->count()) { $cor = Cor::where('nome', 'LavenderBlush')->first(); $cor->nome = 'LavenderBlush'; $cor->hexadecimal = '#FFF0F5'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LavenderBlush'; $cor->hexadecimal = '#FFF0F5'; $cor->save(); }
      if (Cor::where('nome', 'Lavender')->count()) { $cor = Cor::where('nome', 'Lavender')->first(); $cor->nome = 'Lavender'; $cor->hexadecimal = '#E6E6FA'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Lavender'; $cor->hexadecimal = '#E6E6FA'; $cor->save(); }
      if (Cor::where('nome', 'Thistle')->count()) { $cor = Cor::where('nome', 'Thistle')->first(); $cor->nome = 'Thistle'; $cor->hexadecimal = '#D8BFD8'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Thistle'; $cor->hexadecimal = '#D8BFD8'; $cor->save(); }
      if (Cor::where('nome', 'Azure')->count()) { $cor = Cor::where('nome', 'Azure')->first(); $cor->nome = 'Azure'; $cor->hexadecimal = '#F0FFFF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Azure'; $cor->hexadecimal = '#F0FFFF'; $cor->save(); }
      if (Cor::where('nome', 'LightCyan')->count()) { $cor = Cor::where('nome', 'LightCyan')->first(); $cor->nome = 'LightCyan'; $cor->hexadecimal = '#E0FFFF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'LightCyan'; $cor->hexadecimal = '#E0FFFF'; $cor->save(); }
      if (Cor::where('nome', 'PowderBlue')->count()) { $cor = Cor::where('nome', 'PowderBlue')->first(); $cor->nome = 'PowderBlue'; $cor->hexadecimal = '#B0E0E6'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'PowderBlue'; $cor->hexadecimal = '#B0E0E6'; $cor->save(); }
      if (Cor::where('nome', 'PaleTurquoise')->count()) { $cor = Cor::where('nome', 'PaleTurquoise')->first(); $cor->nome = 'PaleTurquoise'; $cor->hexadecimal = '#E0FFFF'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'PaleTurquoise'; $cor->hexadecimal = '#E0FFFF'; $cor->save(); }
      if (Cor::where('nome', 'Honeydew')->count()) { $cor = Cor::where('nome', 'Honeydew')->first(); $cor->nome = 'Honeydew'; $cor->hexadecimal = '#F0FFF0'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'Honeydew'; $cor->hexadecimal = '#F0FFF0'; $cor->save(); }
      if (Cor::where('nome', 'MintCream')->count()) { $cor = Cor::where('nome', 'MintCream')->first(); $cor->nome = 'MintCream'; $cor->hexadecimal = '#F5FFFA'; $cor->update(); } else { $cor = new Cor(); $cor->nome = 'MintCream'; $cor->hexadecimal = '#F5FFFA'; $cor->save(); }
    }
}
